Update patch set 3
Patch Set 3:

Causes compile error

Import includes file: /home/mardon/android/system/out/target/product/anzu/obj/STATIC_LIBRARIES/libloc_api-rpc_intermediates/import_includes
target Java: CyanogenSetupWizard (/home/mardon/android/system/out/target/common/obj/APPS/CyanogenSetupWizard_intermediates/classes)
packages/apps/SetupWizard/src/com/cyanogenmod/setupwizard/setup/WelcomePage.java:42: error: cannot find symbol
import com.android.internal.telephony.MccTable;
                                     ^
  symbol:   class MccTable
  location: package com.android.internal.telephony
packages/apps/SetupWizard/src/com/cyanogenmod/setupwizard/setup/WelcomePage.java:320: error: cannot find symbol
                    locale = MccTable.getLocaleFromMcc(activity, mcc, null);
                             ^
  symbol:   variable MccTable
  location: class WelcomeFragment.FetchUpdateSimLocaleTask
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: packages/apps/SetupWizard/src/com/cyanogenmod/setupwizard/setup/DateTimePage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
build/core/java.mk:394: recipe for target '/home/mardon/android/system/out/target/common/obj/APPS/CyanogenSetupWizard_intermediates/classes-full-debug.jar' failed
make: *** [/home/mardon/android/system/out/target/common/obj/APPS/CyanogenSetupWizard_intermediates/classes-full-debug.jar] Error 41
make: Leaving directory '/home/mardon/android/system'

#### make failed to build some targets

Patch-set: 3
Reviewer: Markus Menzel <5681@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0